//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HugoWorld.Services {
    using System.Runtime.Serialization;
    using System;

    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HeroDTO", Namespace="http://schemas.datacontract.org/2004/07/HugoWorld.WCF.DTOs")]
    [System.SerializableAttribute()]
    public partial class HeroDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClasseIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CompteJoueurIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EstConnecteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ExperienceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MondeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long NiveauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomHeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatDexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatIntField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatStrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatVitaliteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int xField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int yField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClasseId {
            get {
                return this.ClasseIdField;
            }
            set {
                if ((this.ClasseIdField.Equals(value) != true)) {
                    this.ClasseIdField = value;
                    this.RaisePropertyChanged("ClasseId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CompteJoueurId {
            get {
                return this.CompteJoueurIdField;
            }
            set {
                if ((this.CompteJoueurIdField.Equals(value) != true)) {
                    this.CompteJoueurIdField = value;
                    this.RaisePropertyChanged("CompteJoueurId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EstConnecte {
            get {
                return this.EstConnecteField;
            }
            set {
                if ((this.EstConnecteField.Equals(value) != true)) {
                    this.EstConnecteField = value;
                    this.RaisePropertyChanged("EstConnecte");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Experience {
            get {
                return this.ExperienceField;
            }
            set {
                if ((this.ExperienceField.Equals(value) != true)) {
                    this.ExperienceField = value;
                    this.RaisePropertyChanged("Experience");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MondeId {
            get {
                return this.MondeIdField;
            }
            set {
                if ((this.MondeIdField.Equals(value) != true)) {
                    this.MondeIdField = value;
                    this.RaisePropertyChanged("MondeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Niveau {
            get {
                return this.NiveauField;
            }
            set {
                if ((this.NiveauField.Equals(value) != true)) {
                    this.NiveauField = value;
                    this.RaisePropertyChanged("Niveau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomHero {
            get {
                return this.NomHeroField;
            }
            set {
                if ((object.ReferenceEquals(this.NomHeroField, value) != true)) {
                    this.NomHeroField = value;
                    this.RaisePropertyChanged("NomHero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatDex {
            get {
                return this.StatDexField;
            }
            set {
                if ((this.StatDexField.Equals(value) != true)) {
                    this.StatDexField = value;
                    this.RaisePropertyChanged("StatDex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatInt {
            get {
                return this.StatIntField;
            }
            set {
                if ((this.StatIntField.Equals(value) != true)) {
                    this.StatIntField = value;
                    this.RaisePropertyChanged("StatInt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatStr {
            get {
                return this.StatStrField;
            }
            set {
                if ((this.StatStrField.Equals(value) != true)) {
                    this.StatStrField = value;
                    this.RaisePropertyChanged("StatStr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatVitalite {
            get {
                return this.StatVitaliteField;
            }
            set {
                if ((this.StatVitaliteField.Equals(value) != true)) {
                    this.StatVitaliteField = value;
                    this.RaisePropertyChanged("StatVitalite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int x {
            get {
                return this.xField;
            }
            set {
                if ((this.xField.Equals(value) != true)) {
                    this.xField = value;
                    this.RaisePropertyChanged("x");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int y {
            get {
                return this.yField;
            }
            set {
                if ((this.yField.Equals(value) != true)) {
                    this.yField = value;
                    this.RaisePropertyChanged("y");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompteJoueurDTO", Namespace="http://schemas.datacontract.org/2004/07/HugoWorld.WCF.DTOs")]
    [System.SerializableAttribute()]
    public partial class CompteJoueurDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CourrielField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] MotDePasseHashField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomJoueurField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrenomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid SaltField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TypeUtilisateurField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Courriel {
            get {
                return this.CourrielField;
            }
            set {
                if ((object.ReferenceEquals(this.CourrielField, value) != true)) {
                    this.CourrielField = value;
                    this.RaisePropertyChanged("Courriel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] MotDePasseHash {
            get {
                return this.MotDePasseHashField;
            }
            set {
                if ((object.ReferenceEquals(this.MotDePasseHashField, value) != true)) {
                    this.MotDePasseHashField = value;
                    this.RaisePropertyChanged("MotDePasseHash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomJoueur {
            get {
                return this.NomJoueurField;
            }
            set {
                if ((object.ReferenceEquals(this.NomJoueurField, value) != true)) {
                    this.NomJoueurField = value;
                    this.RaisePropertyChanged("NomJoueur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prenom {
            get {
                return this.PrenomField;
            }
            set {
                if ((object.ReferenceEquals(this.PrenomField, value) != true)) {
                    this.PrenomField = value;
                    this.RaisePropertyChanged("Prenom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Salt {
            get {
                return this.SaltField;
            }
            set {
                if ((this.SaltField.Equals(value) != true)) {
                    this.SaltField = value;
                    this.RaisePropertyChanged("Salt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TypeUtilisateur {
            get {
                return this.TypeUtilisateurField;
            }
            set {
                if ((this.TypeUtilisateurField.Equals(value) != true)) {
                    this.TypeUtilisateurField = value;
                    this.RaisePropertyChanged("TypeUtilisateur");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Services.IJoueurService")]
    public interface IJoueurService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoueurService/Connection", ReplyAction="http://tempuri.org/IJoueurService/ConnectionResponse")]
        string Connection(string p_Username, string p_Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoueurService/Connection", ReplyAction="http://tempuri.org/IJoueurService/ConnectionResponse")]
        System.Threading.Tasks.Task<string> ConnectionAsync(string p_Username, string p_Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoueurService/GetHeroesByAccountId", ReplyAction="http://tempuri.org/IJoueurService/GetHeroesByAccountIdResponse")]
        Services.HeroDTO[] GetHeroesByAccountId(int p_Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoueurService/GetHeroesByAccountId", ReplyAction="http://tempuri.org/IJoueurService/GetHeroesByAccountIdResponse")]
        System.Threading.Tasks.Task<Services.HeroDTO[]> GetHeroesByAccountIdAsync(int p_Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoueurService/GetAccountByName", ReplyAction="http://tempuri.org/IJoueurService/GetAccountByNameResponse")]
        Services.CompteJoueurDTO GetAccountByName(string p_Username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoueurService/GetAccountByName", ReplyAction="http://tempuri.org/IJoueurService/GetAccountByNameResponse")]
        System.Threading.Tasks.Task<Services.CompteJoueurDTO> GetAccountByNameAsync(string p_Username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJoueurServiceChannel : Services.IJoueurService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JoueurServiceClient : System.ServiceModel.ClientBase<Services.IJoueurService>, Services.IJoueurService {
        
        public JoueurServiceClient() {
        }
        
        public JoueurServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JoueurServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JoueurServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JoueurServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Connection(string p_Username, string p_Password) {
            return base.Channel.Connection(p_Username, p_Password);
        }
        
        public System.Threading.Tasks.Task<string> ConnectionAsync(string p_Username, string p_Password) {
            return base.Channel.ConnectionAsync(p_Username, p_Password);
        }
        
        public Services.HeroDTO[] GetHeroesByAccountId(int p_Id) {
            return base.Channel.GetHeroesByAccountId(p_Id);
        }
        
        public System.Threading.Tasks.Task<Services.HeroDTO[]> GetHeroesByAccountIdAsync(int p_Id) {
            return base.Channel.GetHeroesByAccountIdAsync(p_Id);
        }
        
        public Services.CompteJoueurDTO GetAccountByName(string p_Username) {
            return base.Channel.GetAccountByName(p_Username);
        }
        
        public System.Threading.Tasks.Task<Services.CompteJoueurDTO> GetAccountByNameAsync(string p_Username) {
            return base.Channel.GetAccountByNameAsync(p_Username);
        }
    }
}
