//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HugoWorld_Client.HL_Services {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HeroDTO", Namespace="http://schemas.datacontract.org/2004/07/HugoWorld_WCF.DTOs")]
    [System.SerializableAttribute()]
    public partial class HeroDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HugoWorld_Client.HL_Services.ClasseDTO ClasseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClasseIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HugoWorld_Client.HL_Services.CompteJoueurDTO CompteJoueurField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CompteJoueurIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EstConnecteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ExperienceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HugoWorld_Client.HL_Services.InventaireHeroDTO[] InventaireHerosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HugoWorld_Client.HL_Services.ItemDTO[] ItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HugoWorld_Client.HL_Services.MondeDTO MondeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MondeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long NiveauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomHeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatDexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatIntField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatStrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatVitaliteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int xField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int yField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HugoWorld_Client.HL_Services.ClasseDTO Classe {
            get {
                return this.ClasseField;
            }
            set {
                if ((object.ReferenceEquals(this.ClasseField, value) != true)) {
                    this.ClasseField = value;
                    this.RaisePropertyChanged("Classe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClasseId {
            get {
                return this.ClasseIdField;
            }
            set {
                if ((this.ClasseIdField.Equals(value) != true)) {
                    this.ClasseIdField = value;
                    this.RaisePropertyChanged("ClasseId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HugoWorld_Client.HL_Services.CompteJoueurDTO CompteJoueur {
            get {
                return this.CompteJoueurField;
            }
            set {
                if ((object.ReferenceEquals(this.CompteJoueurField, value) != true)) {
                    this.CompteJoueurField = value;
                    this.RaisePropertyChanged("CompteJoueur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CompteJoueurId {
            get {
                return this.CompteJoueurIdField;
            }
            set {
                if ((this.CompteJoueurIdField.Equals(value) != true)) {
                    this.CompteJoueurIdField = value;
                    this.RaisePropertyChanged("CompteJoueurId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EstConnecte {
            get {
                return this.EstConnecteField;
            }
            set {
                if ((this.EstConnecteField.Equals(value) != true)) {
                    this.EstConnecteField = value;
                    this.RaisePropertyChanged("EstConnecte");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Experience {
            get {
                return this.ExperienceField;
            }
            set {
                if ((this.ExperienceField.Equals(value) != true)) {
                    this.ExperienceField = value;
                    this.RaisePropertyChanged("Experience");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HugoWorld_Client.HL_Services.InventaireHeroDTO[] InventaireHeros {
            get {
                return this.InventaireHerosField;
            }
            set {
                if ((object.ReferenceEquals(this.InventaireHerosField, value) != true)) {
                    this.InventaireHerosField = value;
                    this.RaisePropertyChanged("InventaireHeros");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HugoWorld_Client.HL_Services.ItemDTO[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HugoWorld_Client.HL_Services.MondeDTO Monde {
            get {
                return this.MondeField;
            }
            set {
                if ((object.ReferenceEquals(this.MondeField, value) != true)) {
                    this.MondeField = value;
                    this.RaisePropertyChanged("Monde");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MondeId {
            get {
                return this.MondeIdField;
            }
            set {
                if ((this.MondeIdField.Equals(value) != true)) {
                    this.MondeIdField = value;
                    this.RaisePropertyChanged("MondeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Niveau {
            get {
                return this.NiveauField;
            }
            set {
                if ((this.NiveauField.Equals(value) != true)) {
                    this.NiveauField = value;
                    this.RaisePropertyChanged("Niveau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomHero {
            get {
                return this.NomHeroField;
            }
            set {
                if ((object.ReferenceEquals(this.NomHeroField, value) != true)) {
                    this.NomHeroField = value;
                    this.RaisePropertyChanged("NomHero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatDex {
            get {
                return this.StatDexField;
            }
            set {
                if ((this.StatDexField.Equals(value) != true)) {
                    this.StatDexField = value;
                    this.RaisePropertyChanged("StatDex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatInt {
            get {
                return this.StatIntField;
            }
            set {
                if ((this.StatIntField.Equals(value) != true)) {
                    this.StatIntField = value;
                    this.RaisePropertyChanged("StatInt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatStr {
            get {
                return this.StatStrField;
            }
            set {
                if ((this.StatStrField.Equals(value) != true)) {
                    this.StatStrField = value;
                    this.RaisePropertyChanged("StatStr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatVitalite {
            get {
                return this.StatVitaliteField;
            }
            set {
                if ((this.StatVitaliteField.Equals(value) != true)) {
                    this.StatVitaliteField = value;
                    this.RaisePropertyChanged("StatVitalite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int x {
            get {
                return this.xField;
            }
            set {
                if ((this.xField.Equals(value) != true)) {
                    this.xField = value;
                    this.RaisePropertyChanged("x");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int y {
            get {
                return this.yField;
            }
            set {
                if ((this.yField.Equals(value) != true)) {
                    this.yField = value;
                    this.RaisePropertyChanged("y");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClasseDTO", Namespace="http://schemas.datacontract.org/2004/07/HugoWorld_WCF.DTOs")]
    [System.SerializableAttribute()]
    public partial class ClasseDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescrpitionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HugoWorld_Client.HL_Services.HeroDTO[] HerosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HugoWorld_Client.HL_Services.MondeDTO MondeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MondeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomClasseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatBaseDexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatBaseIntField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatBaseStrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatBaseVitaliteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descrpition {
            get {
                return this.DescrpitionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescrpitionField, value) != true)) {
                    this.DescrpitionField = value;
                    this.RaisePropertyChanged("Descrpition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HugoWorld_Client.HL_Services.HeroDTO[] Heros {
            get {
                return this.HerosField;
            }
            set {
                if ((object.ReferenceEquals(this.HerosField, value) != true)) {
                    this.HerosField = value;
                    this.RaisePropertyChanged("Heros");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HugoWorld_Client.HL_Services.MondeDTO Monde {
            get {
                return this.MondeField;
            }
            set {
                if ((object.ReferenceEquals(this.MondeField, value) != true)) {
                    this.MondeField = value;
                    this.RaisePropertyChanged("Monde");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MondeId {
            get {
                return this.MondeIdField;
            }
            set {
                if ((this.MondeIdField.Equals(value) != true)) {
                    this.MondeIdField = value;
                    this.RaisePropertyChanged("MondeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomClasse {
            get {
                return this.NomClasseField;
            }
            set {
                if ((object.ReferenceEquals(this.NomClasseField, value) != true)) {
                    this.NomClasseField = value;
                    this.RaisePropertyChanged("NomClasse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatBaseDex {
            get {
                return this.StatBaseDexField;
            }
            set {
                if ((this.StatBaseDexField.Equals(value) != true)) {
                    this.StatBaseDexField = value;
                    this.RaisePropertyChanged("StatBaseDex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatBaseInt {
            get {
                return this.StatBaseIntField;
            }
            set {
                if ((this.StatBaseIntField.Equals(value) != true)) {
                    this.StatBaseIntField = value;
                    this.RaisePropertyChanged("StatBaseInt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatBaseStr {
            get {
                return this.StatBaseStrField;
            }
            set {
                if ((this.StatBaseStrField.Equals(value) != true)) {
                    this.StatBaseStrField = value;
                    this.RaisePropertyChanged("StatBaseStr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatBaseVitalite {
            get {
                return this.StatBaseVitaliteField;
            }
            set {
                if ((this.StatBaseVitaliteField.Equals(value) != true)) {
                    this.StatBaseVitaliteField = value;
                    this.RaisePropertyChanged("StatBaseVitalite");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompteJoueurDTO", Namespace="http://schemas.datacontract.org/2004/07/HugoWorld_WCF.DTOs")]
    [System.SerializableAttribute()]
    public partial class CompteJoueurDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CourrielField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HugoWorld_Client.HL_Services.HeroDTO[] HerosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] MotDePasseHashField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomJoueurField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrenomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid SaltField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TypeUtilisateurField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Courriel {
            get {
                return this.CourrielField;
            }
            set {
                if ((object.ReferenceEquals(this.CourrielField, value) != true)) {
                    this.CourrielField = value;
                    this.RaisePropertyChanged("Courriel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HugoWorld_Client.HL_Services.HeroDTO[] Heros {
            get {
                return this.HerosField;
            }
            set {
                if ((object.ReferenceEquals(this.HerosField, value) != true)) {
                    this.HerosField = value;
                    this.RaisePropertyChanged("Heros");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] MotDePasseHash {
            get {
                return this.MotDePasseHashField;
            }
            set {
                if ((object.ReferenceEquals(this.MotDePasseHashField, value) != true)) {
                    this.MotDePasseHashField = value;
                    this.RaisePropertyChanged("MotDePasseHash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomJoueur {
            get {
                return this.NomJoueurField;
            }
            set {
                if ((object.ReferenceEquals(this.NomJoueurField, value) != true)) {
                    this.NomJoueurField = value;
                    this.RaisePropertyChanged("NomJoueur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prenom {
            get {
                return this.PrenomField;
            }
            set {
                if ((object.ReferenceEquals(this.PrenomField, value) != true)) {
                    this.PrenomField = value;
                    this.RaisePropertyChanged("Prenom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Salt {
            get {
                return this.SaltField;
            }
            set {
                if ((this.SaltField.Equals(value) != true)) {
                    this.SaltField = value;
                    this.RaisePropertyChanged("Salt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TypeUtilisateur {
            get {
                return this.TypeUtilisateurField;
            }
            set {
                if ((this.TypeUtilisateurField.Equals(value) != true)) {
                    this.TypeUtilisateurField = value;
                    this.RaisePropertyChanged("TypeUtilisateur");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MondeDTO", Namespace="http://schemas.datacontract.org/2004/07/HugoWorld_WCF.DTOs")]
    [System.SerializableAttribute()]
    public partial class MondeDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HugoWorld_Client.HL_Services.ClasseDTO[] ClassesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HugoWorld_Client.HL_Services.HeroDTO[] HerosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HugoWorld_Client.HL_Services.ItemDTO[] ItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LimiteXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LimiteYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HugoWorld_Client.HL_Services.MondeDTO[] MonstresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HugoWorld_Client.HL_Services.ObjetMondeDTO[] ObjetMondesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HugoWorld_Client.HL_Services.ClasseDTO[] Classes {
            get {
                return this.ClassesField;
            }
            set {
                if ((object.ReferenceEquals(this.ClassesField, value) != true)) {
                    this.ClassesField = value;
                    this.RaisePropertyChanged("Classes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HugoWorld_Client.HL_Services.HeroDTO[] Heros {
            get {
                return this.HerosField;
            }
            set {
                if ((object.ReferenceEquals(this.HerosField, value) != true)) {
                    this.HerosField = value;
                    this.RaisePropertyChanged("Heros");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HugoWorld_Client.HL_Services.ItemDTO[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LimiteX {
            get {
                return this.LimiteXField;
            }
            set {
                if ((this.LimiteXField.Equals(value) != true)) {
                    this.LimiteXField = value;
                    this.RaisePropertyChanged("LimiteX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LimiteY {
            get {
                return this.LimiteYField;
            }
            set {
                if ((this.LimiteYField.Equals(value) != true)) {
                    this.LimiteYField = value;
                    this.RaisePropertyChanged("LimiteY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HugoWorld_Client.HL_Services.MondeDTO[] Monstres {
            get {
                return this.MonstresField;
            }
            set {
                if ((object.ReferenceEquals(this.MonstresField, value) != true)) {
                    this.MonstresField = value;
                    this.RaisePropertyChanged("Monstres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HugoWorld_Client.HL_Services.ObjetMondeDTO[] ObjetMondes {
            get {
                return this.ObjetMondesField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjetMondesField, value) != true)) {
                    this.ObjetMondesField = value;
                    this.RaisePropertyChanged("ObjetMondes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InventaireHeroDTO", Namespace="http://schemas.datacontract.org/2004/07/HugoWorld_WCF.DTOs")]
    [System.SerializableAttribute()]
    public partial class InventaireHeroDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HugoWorld_Client.HL_Services.HeroDTO HeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdHeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdInventaireHeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HugoWorld_Client.HL_Services.ItemDTO ItemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ItemIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantiteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HugoWorld_Client.HL_Services.HeroDTO Hero {
            get {
                return this.HeroField;
            }
            set {
                if ((object.ReferenceEquals(this.HeroField, value) != true)) {
                    this.HeroField = value;
                    this.RaisePropertyChanged("Hero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdHero {
            get {
                return this.IdHeroField;
            }
            set {
                if ((this.IdHeroField.Equals(value) != true)) {
                    this.IdHeroField = value;
                    this.RaisePropertyChanged("IdHero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdInventaireHero {
            get {
                return this.IdInventaireHeroField;
            }
            set {
                if ((this.IdInventaireHeroField.Equals(value) != true)) {
                    this.IdInventaireHeroField = value;
                    this.RaisePropertyChanged("IdInventaireHero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HugoWorld_Client.HL_Services.ItemDTO Item {
            get {
                return this.ItemField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemField, value) != true)) {
                    this.ItemField = value;
                    this.RaisePropertyChanged("Item");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ItemId {
            get {
                return this.ItemIdField;
            }
            set {
                if ((this.ItemIdField.Equals(value) != true)) {
                    this.ItemIdField = value;
                    this.RaisePropertyChanged("ItemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantite {
            get {
                return this.QuantiteField;
            }
            set {
                if ((this.QuantiteField.Equals(value) != true)) {
                    this.QuantiteField = value;
                    this.RaisePropertyChanged("Quantite");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItemDTO", Namespace="http://schemas.datacontract.org/2004/07/HugoWorld_WCF.DTOs")]
    [System.SerializableAttribute()]
    public partial class ItemDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HugoWorld_Client.HL_Services.EffetItemDTO[] EffetsItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HugoWorld_Client.HL_Services.HeroDTO HeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdHeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ImageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HugoWorld_Client.HL_Services.InventaireHeroDTO[] InventaireHeroDTOsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HugoWorld_Client.HL_Services.MondeDTO MondeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MondeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int xField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int yField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HugoWorld_Client.HL_Services.EffetItemDTO[] EffetsItems {
            get {
                return this.EffetsItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.EffetsItemsField, value) != true)) {
                    this.EffetsItemsField = value;
                    this.RaisePropertyChanged("EffetsItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HugoWorld_Client.HL_Services.HeroDTO Hero {
            get {
                return this.HeroField;
            }
            set {
                if ((object.ReferenceEquals(this.HeroField, value) != true)) {
                    this.HeroField = value;
                    this.RaisePropertyChanged("Hero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdHero {
            get {
                return this.IdHeroField;
            }
            set {
                if ((this.IdHeroField.Equals(value) != true)) {
                    this.IdHeroField = value;
                    this.RaisePropertyChanged("IdHero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ImageId {
            get {
                return this.ImageIdField;
            }
            set {
                if ((this.ImageIdField.Equals(value) != true)) {
                    this.ImageIdField = value;
                    this.RaisePropertyChanged("ImageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HugoWorld_Client.HL_Services.InventaireHeroDTO[] InventaireHeroDTOs {
            get {
                return this.InventaireHeroDTOsField;
            }
            set {
                if ((object.ReferenceEquals(this.InventaireHeroDTOsField, value) != true)) {
                    this.InventaireHeroDTOsField = value;
                    this.RaisePropertyChanged("InventaireHeroDTOs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HugoWorld_Client.HL_Services.MondeDTO Monde {
            get {
                return this.MondeField;
            }
            set {
                if ((object.ReferenceEquals(this.MondeField, value) != true)) {
                    this.MondeField = value;
                    this.RaisePropertyChanged("Monde");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MondeId {
            get {
                return this.MondeIdField;
            }
            set {
                if ((this.MondeIdField.Equals(value) != true)) {
                    this.MondeIdField = value;
                    this.RaisePropertyChanged("MondeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int x {
            get {
                return this.xField;
            }
            set {
                if ((this.xField.Equals(value) != true)) {
                    this.xField = value;
                    this.RaisePropertyChanged("x");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int y {
            get {
                return this.yField;
            }
            set {
                if ((this.yField.Equals(value) != true)) {
                    this.yField = value;
                    this.RaisePropertyChanged("y");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObjetMondeDTO", Namespace="http://schemas.datacontract.org/2004/07/HugoWorld_WCF.DTOs")]
    [System.SerializableAttribute()]
    public partial class ObjetMondeDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ImageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HugoWorld_Client.HL_Services.MondeDTO MondeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MondeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TypeObjetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int xField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int yField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ImageId {
            get {
                return this.ImageIdField;
            }
            set {
                if ((this.ImageIdField.Equals(value) != true)) {
                    this.ImageIdField = value;
                    this.RaisePropertyChanged("ImageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HugoWorld_Client.HL_Services.MondeDTO Monde {
            get {
                return this.MondeField;
            }
            set {
                if ((object.ReferenceEquals(this.MondeField, value) != true)) {
                    this.MondeField = value;
                    this.RaisePropertyChanged("Monde");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MondeId {
            get {
                return this.MondeIdField;
            }
            set {
                if ((this.MondeIdField.Equals(value) != true)) {
                    this.MondeIdField = value;
                    this.RaisePropertyChanged("MondeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TypeObjet {
            get {
                return this.TypeObjetField;
            }
            set {
                if ((this.TypeObjetField.Equals(value) != true)) {
                    this.TypeObjetField = value;
                    this.RaisePropertyChanged("TypeObjet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int x {
            get {
                return this.xField;
            }
            set {
                if ((this.xField.Equals(value) != true)) {
                    this.xField = value;
                    this.RaisePropertyChanged("x");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int y {
            get {
                return this.yField;
            }
            set {
                if ((this.yField.Equals(value) != true)) {
                    this.yField = value;
                    this.RaisePropertyChanged("y");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EffetItemDTO", Namespace="http://schemas.datacontract.org/2004/07/HugoWorld_WCF.DTOs")]
    [System.SerializableAttribute()]
    public partial class EffetItemDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HugoWorld_Client.HL_Services.ItemDTO ItemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ItemIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TypeEffetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ValeurEffetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HugoWorld_Client.HL_Services.ItemDTO Item {
            get {
                return this.ItemField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemField, value) != true)) {
                    this.ItemField = value;
                    this.RaisePropertyChanged("Item");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ItemId {
            get {
                return this.ItemIdField;
            }
            set {
                if ((this.ItemIdField.Equals(value) != true)) {
                    this.ItemIdField = value;
                    this.RaisePropertyChanged("ItemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TypeEffet {
            get {
                return this.TypeEffetField;
            }
            set {
                if ((this.TypeEffetField.Equals(value) != true)) {
                    this.TypeEffetField = value;
                    this.RaisePropertyChanged("TypeEffet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ValeurEffet {
            get {
                return this.ValeurEffetField;
            }
            set {
                if ((this.ValeurEffetField.Equals(value) != true)) {
                    this.ValeurEffetField = value;
                    this.RaisePropertyChanged("ValeurEffet");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HL_Services.IJoueurService")]
    public interface IJoueurService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoueurService/Connection", ReplyAction="http://tempuri.org/IJoueurService/ConnectionResponse")]
        string Connection(string p_Username, string p_Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoueurService/Connection", ReplyAction="http://tempuri.org/IJoueurService/ConnectionResponse")]
        System.Threading.Tasks.Task<string> ConnectionAsync(string p_Username, string p_Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoueurService/GetHeroesByAccountId", ReplyAction="http://tempuri.org/IJoueurService/GetHeroesByAccountIdResponse")]
        HugoWorld_Client.HL_Services.HeroDTO[] GetHeroesByAccountId(int p_Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoueurService/GetHeroesByAccountId", ReplyAction="http://tempuri.org/IJoueurService/GetHeroesByAccountIdResponse")]
        System.Threading.Tasks.Task<HugoWorld_Client.HL_Services.HeroDTO[]> GetHeroesByAccountIdAsync(int p_Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoueurService/GetAccountByName", ReplyAction="http://tempuri.org/IJoueurService/GetAccountByNameResponse")]
        HugoWorld_Client.HL_Services.CompteJoueurDTO GetAccountByName(string p_Username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoueurService/GetAccountByName", ReplyAction="http://tempuri.org/IJoueurService/GetAccountByNameResponse")]
        System.Threading.Tasks.Task<HugoWorld_Client.HL_Services.CompteJoueurDTO> GetAccountByNameAsync(string p_Username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJoueurServiceChannel : HugoWorld_Client.HL_Services.IJoueurService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JoueurServiceClient : System.ServiceModel.ClientBase<HugoWorld_Client.HL_Services.IJoueurService>, HugoWorld_Client.HL_Services.IJoueurService {
        
        public JoueurServiceClient() {
        }
        
        public JoueurServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JoueurServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JoueurServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JoueurServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Connection(string p_Username, string p_Password) {
            return base.Channel.Connection(p_Username, p_Password);
        }
        
        public System.Threading.Tasks.Task<string> ConnectionAsync(string p_Username, string p_Password) {
            return base.Channel.ConnectionAsync(p_Username, p_Password);
        }
        
        public HugoWorld_Client.HL_Services.HeroDTO[] GetHeroesByAccountId(int p_Id) {
            return base.Channel.GetHeroesByAccountId(p_Id);
        }
        
        public System.Threading.Tasks.Task<HugoWorld_Client.HL_Services.HeroDTO[]> GetHeroesByAccountIdAsync(int p_Id) {
            return base.Channel.GetHeroesByAccountIdAsync(p_Id);
        }
        
        public HugoWorld_Client.HL_Services.CompteJoueurDTO GetAccountByName(string p_Username) {
            return base.Channel.GetAccountByName(p_Username);
        }
        
        public System.Threading.Tasks.Task<HugoWorld_Client.HL_Services.CompteJoueurDTO> GetAccountByNameAsync(string p_Username) {
            return base.Channel.GetAccountByNameAsync(p_Username);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HL_Services.IMondeService")]
    public interface IMondeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMondeService/ListWorlds", ReplyAction="http://tempuri.org/IMondeService/ListWorldsResponse")]
        HugoWorld_Client.HL_Services.MondeDTO[] ListWorlds();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMondeService/ListWorlds", ReplyAction="http://tempuri.org/IMondeService/ListWorldsResponse")]
        System.Threading.Tasks.Task<HugoWorld_Client.HL_Services.MondeDTO[]> ListWorldsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMondeServiceChannel : HugoWorld_Client.HL_Services.IMondeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MondeServiceClient : System.ServiceModel.ClientBase<HugoWorld_Client.HL_Services.IMondeService>, HugoWorld_Client.HL_Services.IMondeService {
        
        public MondeServiceClient() {
        }
        
        public MondeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MondeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MondeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MondeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HugoWorld_Client.HL_Services.MondeDTO[] ListWorlds() {
            return base.Channel.ListWorlds();
        }
        
        public System.Threading.Tasks.Task<HugoWorld_Client.HL_Services.MondeDTO[]> ListWorldsAsync() {
            return base.Channel.ListWorldsAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HL_Services.IItemService")]
    public interface IItemService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemService/AddItem", ReplyAction="http://tempuri.org/IItemService/AddItemResponse")]
        void AddItem(string p_Nom, string p_Description, int p_X, int p_Y, int p_ImageId, int p_MondeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemService/AddItem", ReplyAction="http://tempuri.org/IItemService/AddItemResponse")]
        System.Threading.Tasks.Task AddItemAsync(string p_Nom, string p_Description, int p_X, int p_Y, int p_ImageId, int p_MondeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemService/DeleteItemById", ReplyAction="http://tempuri.org/IItemService/DeleteItemByIdResponse")]
        void DeleteItemById(int p_ItemId, HugoWorld_Client.HL_Services.HeroDTO p_Hero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemService/DeleteItemById", ReplyAction="http://tempuri.org/IItemService/DeleteItemByIdResponse")]
        System.Threading.Tasks.Task DeleteItemByIdAsync(int p_ItemId, HugoWorld_Client.HL_Services.HeroDTO p_Hero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemService/EditItemQuantityById", ReplyAction="http://tempuri.org/IItemService/EditItemQuantityByIdResponse")]
        void EditItemQuantityById(int p_ItemId, int p_Quantite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemService/EditItemQuantityById", ReplyAction="http://tempuri.org/IItemService/EditItemQuantityByIdResponse")]
        System.Threading.Tasks.Task EditItemQuantityByIdAsync(int p_ItemId, int p_Quantite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemService/AddRangeItems", ReplyAction="http://tempuri.org/IItemService/AddRangeItemsResponse")]
        void AddRangeItems(HugoWorld_Client.HL_Services.ItemDTO[] lstItems);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemService/AddRangeItems", ReplyAction="http://tempuri.org/IItemService/AddRangeItemsResponse")]
        System.Threading.Tasks.Task AddRangeItemsAsync(HugoWorld_Client.HL_Services.ItemDTO[] lstItems);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemService/RemoveRangeById", ReplyAction="http://tempuri.org/IItemService/RemoveRangeByIdResponse")]
        void RemoveRangeById(int p_ItemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemService/RemoveRangeById", ReplyAction="http://tempuri.org/IItemService/RemoveRangeByIdResponse")]
        System.Threading.Tasks.Task RemoveRangeByIdAsync(int p_ItemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemService/AddItemEffectById", ReplyAction="http://tempuri.org/IItemService/AddItemEffectByIdResponse")]
        void AddItemEffectById(int p_ItemId, int p_ValeurEffet, int p_TypeEffet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemService/AddItemEffectById", ReplyAction="http://tempuri.org/IItemService/AddItemEffectByIdResponse")]
        System.Threading.Tasks.Task AddItemEffectByIdAsync(int p_ItemId, int p_ValeurEffet, int p_TypeEffet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemService/DeleteItemEffectById", ReplyAction="http://tempuri.org/IItemService/DeleteItemEffectByIdResponse")]
        void DeleteItemEffectById(int p_EffetItemId, int p_ItemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemService/DeleteItemEffectById", ReplyAction="http://tempuri.org/IItemService/DeleteItemEffectByIdResponse")]
        System.Threading.Tasks.Task DeleteItemEffectByIdAsync(int p_EffetItemId, int p_ItemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemService/EditItemEffectById", ReplyAction="http://tempuri.org/IItemService/EditItemEffectByIdResponse")]
        void EditItemEffectById(int p_ItemId, int p_EffetItemId, int p_ValeurEffet, int p_TypeEffet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemService/EditItemEffectById", ReplyAction="http://tempuri.org/IItemService/EditItemEffectByIdResponse")]
        System.Threading.Tasks.Task EditItemEffectByIdAsync(int p_ItemId, int p_EffetItemId, int p_ValeurEffet, int p_TypeEffet);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IItemServiceChannel : HugoWorld_Client.HL_Services.IItemService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ItemServiceClient : System.ServiceModel.ClientBase<HugoWorld_Client.HL_Services.IItemService>, HugoWorld_Client.HL_Services.IItemService {
        
        public ItemServiceClient() {
        }
        
        public ItemServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ItemServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ItemServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ItemServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddItem(string p_Nom, string p_Description, int p_X, int p_Y, int p_ImageId, int p_MondeId) {
            base.Channel.AddItem(p_Nom, p_Description, p_X, p_Y, p_ImageId, p_MondeId);
        }
        
        public System.Threading.Tasks.Task AddItemAsync(string p_Nom, string p_Description, int p_X, int p_Y, int p_ImageId, int p_MondeId) {
            return base.Channel.AddItemAsync(p_Nom, p_Description, p_X, p_Y, p_ImageId, p_MondeId);
        }
        
        public void DeleteItemById(int p_ItemId, HugoWorld_Client.HL_Services.HeroDTO p_Hero) {
            base.Channel.DeleteItemById(p_ItemId, p_Hero);
        }
        
        public System.Threading.Tasks.Task DeleteItemByIdAsync(int p_ItemId, HugoWorld_Client.HL_Services.HeroDTO p_Hero) {
            return base.Channel.DeleteItemByIdAsync(p_ItemId, p_Hero);
        }
        
        public void EditItemQuantityById(int p_ItemId, int p_Quantite) {
            base.Channel.EditItemQuantityById(p_ItemId, p_Quantite);
        }
        
        public System.Threading.Tasks.Task EditItemQuantityByIdAsync(int p_ItemId, int p_Quantite) {
            return base.Channel.EditItemQuantityByIdAsync(p_ItemId, p_Quantite);
        }
        
        public void AddRangeItems(HugoWorld_Client.HL_Services.ItemDTO[] lstItems) {
            base.Channel.AddRangeItems(lstItems);
        }
        
        public System.Threading.Tasks.Task AddRangeItemsAsync(HugoWorld_Client.HL_Services.ItemDTO[] lstItems) {
            return base.Channel.AddRangeItemsAsync(lstItems);
        }
        
        public void RemoveRangeById(int p_ItemId) {
            base.Channel.RemoveRangeById(p_ItemId);
        }
        
        public System.Threading.Tasks.Task RemoveRangeByIdAsync(int p_ItemId) {
            return base.Channel.RemoveRangeByIdAsync(p_ItemId);
        }
        
        public void AddItemEffectById(int p_ItemId, int p_ValeurEffet, int p_TypeEffet) {
            base.Channel.AddItemEffectById(p_ItemId, p_ValeurEffet, p_TypeEffet);
        }
        
        public System.Threading.Tasks.Task AddItemEffectByIdAsync(int p_ItemId, int p_ValeurEffet, int p_TypeEffet) {
            return base.Channel.AddItemEffectByIdAsync(p_ItemId, p_ValeurEffet, p_TypeEffet);
        }
        
        public void DeleteItemEffectById(int p_EffetItemId, int p_ItemId) {
            base.Channel.DeleteItemEffectById(p_EffetItemId, p_ItemId);
        }
        
        public System.Threading.Tasks.Task DeleteItemEffectByIdAsync(int p_EffetItemId, int p_ItemId) {
            return base.Channel.DeleteItemEffectByIdAsync(p_EffetItemId, p_ItemId);
        }
        
        public void EditItemEffectById(int p_ItemId, int p_EffetItemId, int p_ValeurEffet, int p_TypeEffet) {
            base.Channel.EditItemEffectById(p_ItemId, p_EffetItemId, p_ValeurEffet, p_TypeEffet);
        }
        
        public System.Threading.Tasks.Task EditItemEffectByIdAsync(int p_ItemId, int p_EffetItemId, int p_ValeurEffet, int p_TypeEffet) {
            return base.Channel.EditItemEffectByIdAsync(p_ItemId, p_EffetItemId, p_ValeurEffet, p_TypeEffet);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HL_Services.IClasseService")]
    public interface IClasseService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClasseService/AddClassToDatabase", ReplyAction="http://tempuri.org/IClasseService/AddClassToDatabaseResponse")]
        bool AddClassToDatabase(HugoWorld_Client.HL_Services.ClasseDTO p_Class);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClasseService/AddClassToDatabase", ReplyAction="http://tempuri.org/IClasseService/AddClassToDatabaseResponse")]
        System.Threading.Tasks.Task<bool> AddClassToDatabaseAsync(HugoWorld_Client.HL_Services.ClasseDTO p_Class);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClasseServiceChannel : HugoWorld_Client.HL_Services.IClasseService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClasseServiceClient : System.ServiceModel.ClientBase<HugoWorld_Client.HL_Services.IClasseService>, HugoWorld_Client.HL_Services.IClasseService {
        
        public ClasseServiceClient() {
        }
        
        public ClasseServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClasseServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClasseServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClasseServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AddClassToDatabase(HugoWorld_Client.HL_Services.ClasseDTO p_Class) {
            return base.Channel.AddClassToDatabase(p_Class);
        }
        
        public System.Threading.Tasks.Task<bool> AddClassToDatabaseAsync(HugoWorld_Client.HL_Services.ClasseDTO p_Class) {
            return base.Channel.AddClassToDatabaseAsync(p_Class);
        }
    }
}
